### Refresh Token 테스트
POST http://localhost:8080/auth/refresh
Content-Type: application/json

{
  "refreshToken": "RefreshToken"
}


### 청소 검사 테스트
POST http://localhost:8080/admin/check/101
Content-Type: application/json
Authorization: Bearer AccessToken

{
  "date": "2026-09-05",
  "aPassed": true,
  "aNotpassReason": "A구역 이상 없음",
  "aIndPassed": true,
  "aIndNotpassReason": "",
  "bPassed": true,
  "bNotpassReason": "B구역 이상 없음",
  "bIndPassed": true,
  "bIndNotpassReason": ""
}