spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dhc
    username: root
    password: Whalstj24680!

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

